# Generated by Django 2.1.4 on 2018-12-31 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Apache Helicopter', 'Others')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
